export const COVID_SUCCESS = "COVID_SUCCESS";
export const COVID_FAIL = "COVID_FAIL";
export const COVID_LOADING = "COVID_LOADING";

export const COVID_TOTAL_SUCCESS = "COVID_TOTAL_SUCCESS";
export const COVID_TOTAL_FAIL = "COVID_TOTAL_FAIL";
export const COVID_TOTAL_LOADING = "COVID_TOTAL_LOADING";

export const COVID_HISTORICAL_SUCCESS = "COVID_HISTORICAL_SUCCESS";
export const COVID_HISTORICAL_FAIL = "COVID_HISTORICAL_FAIL";
export const COVID_HISTORICAL_LOADING = "COVID_HISTORICAL_LOADING";